#!/usr/bin/env python3
"""Unit tests for scripts/check_tracker_dependencies.py (#504).

    python3 test/tooling/check_tracker_dependencies_test.py

The check's whole value is that people keep it switched on, which means two
failure modes matter equally: missing a real tracking SDK, and crying wolf over
a package that merely reads like one. Both are tested here, along with the
policy loader — the reviewed data is the claim the check makes, so a file it
would silently half-read is a failure of its own.

The real repository is read, never written. Everything else is built in
temporary directories, and nothing here touches the network.
"""

from __future__ import annotations

import contextlib
import importlib.util
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts"


def _load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, SCRIPTS / filename)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    # Registered before exec: @dataclass resolves annotations through
    # sys.modules, so a module loaded this way but never registered blows up on
    # its first dataclass rather than on anything the tests are about.
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


checker = _load("check_tracker_dependencies", "check_tracker_dependencies.py")

POLICY_PATH = SCRIPTS / "tracker_policy.json"


# A policy small enough to read in full, shaped exactly like the real one. The
# entries are the four that the fixtures below exercise, sorted the way the
# loader insists on.
MINIMAL_POLICY = {
    "version": 1,
    "categories": {
        "analytics": "Analytics SDKs",
        "crash-reporting": "Automatic third-party crash reporting",
    },
    "denylist": [
        {
            "ecosystem": "cargo",
            "match": "exact",
            "identifier": "sentry",
            "category": "crash-reporting",
            "vendor": "Sentry",
            "rationale": "Crash reporting to a Sentry server.",
        },
        {
            "ecosystem": "dart",
            "match": "exact",
            "identifier": "amplitude_flutter",
            "category": "analytics",
            "vendor": "Amplitude",
            "rationale": "Product analytics.",
        },
        {
            "ecosystem": "dart",
            "match": "exact",
            "identifier": "firebase_analytics",
            "category": "analytics",
            "vendor": "Google (Firebase)",
            "rationale": "Reports app events to Google.",
        },
        {
            "ecosystem": "gradle-plugin",
            "match": "exact",
            "identifier": "com.google.gms.google-services",
            "category": "analytics",
            "vendor": "Google",
            "rationale": "Wires the Firebase stack into the build.",
        },
        {
            "ecosystem": "maven",
            "match": "group",
            "identifier": "com.google.firebase",
            "category": "analytics",
            "vendor": "Google (Firebase)",
            "rationale": "Every Firebase artifact is a review trigger.",
        },
    ],
    "exceptions": [],
}


CLEAN_LOCK = """\
# Generated by pub
packages:
  audio_service:
    dependency: "direct main"
    description:
      name: audio_service
      sha256: cb122c7c2639d2a992421ef96b67948ad88c5221da3365ccef1031393a76e044
      url: "https://pub.dev"
    source: hosted
    version: "0.18.18"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"
"""

CLEAN_GRADLE = """\
// A comment mentioning firebase_analytics, which is not a dependency.
plugins {
    id "com.android.application"
    id "kotlin-android"
}

android {
    namespace = "io.github.thezupzup.linthra"
    defaultConfig {
        applicationId = "io.github.thezupzup.linthra"
    }
}
"""

CLEAN_CMAKE = """\
list(APPEND FLUTTER_PLUGIN_LIST
  flutter_secure_storage_linux
  url_launcher_linux
)

list(APPEND FLUTTER_FFI_PLUGIN_LIST
)
"""

CLEAN_CARGO = """\
version = 4

[[package]]
name = "linthra_core"
version = "0.1.0"
"""


def _clean_pub_sources(*names: str) -> str:
    return json.dumps(
        [
            {
                "type": "archive",
                "url": f"https://pub.dev/api/archives/{name}-1.0.0.tar.gz",
                "dest": f".pub-cache/hosted/pub.dev/{name}-1.0.0",
            }
            for name in names
        ]
    )


@contextlib.contextmanager
def tree(
    *,
    lock: str = CLEAN_LOCK,
    gradle: str = CLEAN_GRADLE,
    cmake: str = CLEAN_CMAKE,
    cargo: str = CLEAN_CARGO,
    pub_sources: str | None = None,
):
    """A minimal repository with one of every file the check insists on."""
    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory)
        (root / "flatpak" / "generated" / "sources").mkdir(parents=True)
        (root / "linux" / "flutter").mkdir(parents=True)
        (root / "android" / "app").mkdir(parents=True)
        (root / "native" / "linthra_core").mkdir(parents=True)

        (root / "pubspec.lock").write_text(lock, encoding="utf-8")
        (root / "flatpak" / "generated" / "sources" / "pubspec.json").write_text(
            pub_sources if pub_sources is not None else _clean_pub_sources("audio_service"),
            encoding="utf-8",
        )
        (root / "linux" / "flutter" / "generated_plugins.cmake").write_text(
            cmake, encoding="utf-8"
        )
        (root / "android" / "app" / "build.gradle").write_text(gradle, encoding="utf-8")
        (root / "native" / "linthra_core" / "Cargo.lock").write_text(
            cargo, encoding="utf-8"
        )
        yield root


@contextlib.contextmanager
def policy_file(policy: dict):
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "tracker_policy.json"
        path.write_text(json.dumps(policy, indent=2), encoding="utf-8")
        yield path


def run(root: Path, policy: Path, *extra: str) -> tuple[int, str]:
    """Run the check the way CI does and capture what a reviewer would read."""
    out = io.StringIO()
    err = io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        code = checker.main(["--root", str(root), "--policy", str(policy), *extra])
    return code, out.getvalue() + err.getvalue()


def minimal_policy(**changes) -> dict:
    return {**json.loads(json.dumps(MINIMAL_POLICY)), **changes}


# ---------------------------------------------------------------------------
# The policy data itself
# ---------------------------------------------------------------------------


class PolicyDataTest(unittest.TestCase):
    """The reviewed data has to parse the same way every time, or it is not
    reviewed data — it is a file somebody hopes says what they meant."""

    def test_the_real_policy_loads(self) -> None:
        policy = checker.load_policy(POLICY_PATH)
        self.assertGreater(len(policy.entries), 40)
        self.assertEqual(policy.version, 1)

    def test_loading_is_deterministic(self) -> None:
        first = checker.load_policy(POLICY_PATH)
        second = checker.load_policy(POLICY_PATH)
        self.assertEqual(first.entries, second.entries)
        self.assertEqual(
            [entry.identifier for entry in first.entries],
            [entry.identifier for entry in second.entries],
        )

    def test_every_real_entry_is_explained_and_categorised(self) -> None:
        policy = checker.load_policy(POLICY_PATH)
        for entry in policy.entries:
            with self.subTest(entry=entry.identifier):
                self.assertIn(entry.category, policy.categories)
                self.assertGreater(len(entry.rationale), 20)
                self.assertTrue(entry.vendor.strip())

    def test_the_real_policy_names_the_systems_the_issue_named(self) -> None:
        policy = checker.load_policy(POLICY_PATH)
        named = {entry.identifier for entry in policy.entries}
        for identifier in (
            "firebase_analytics",
            "firebase_crashlytics",
            "sentry_flutter",
            "mixpanel_flutter",
            "amplitude_flutter",
            "adjust_sdk",
            "appsflyer_sdk",
            "facebook_app_events",
            "com.google.android.gms:play-services-analytics",
        ):
            self.assertIn(identifier, named)

    def test_the_real_policy_covers_every_category(self) -> None:
        policy = checker.load_policy(POLICY_PATH)
        used = {entry.category for entry in policy.entries}
        self.assertEqual(used, set(policy.categories))

    def test_an_unsorted_denylist_is_rejected(self) -> None:
        policy = minimal_policy()
        policy["denylist"].reverse()
        with policy_file(policy) as path:
            with self.assertRaisesRegex(checker.PolicyError, "sorted"):
                checker.load_policy(path)

    def test_a_duplicate_entry_is_rejected(self) -> None:
        policy = minimal_policy()
        policy["denylist"].insert(3, json.loads(json.dumps(policy["denylist"][2])))
        with policy_file(policy) as path:
            with self.assertRaisesRegex(checker.PolicyError, "duplicate"):
                checker.load_policy(path)

    def test_a_blank_rationale_is_rejected(self) -> None:
        policy = minimal_policy()
        policy["denylist"][0]["rationale"] = "   "
        with policy_file(policy) as path:
            with self.assertRaisesRegex(checker.PolicyError, "rationale"):
                checker.load_policy(path)

    def test_an_unknown_key_is_rejected(self) -> None:
        policy = minimal_policy()
        policy["denylist"][0]["severity"] = "high"
        with policy_file(policy) as path:
            with self.assertRaisesRegex(checker.PolicyError, "unknown key"):
                checker.load_policy(path)

    def test_an_undeclared_category_is_rejected(self) -> None:
        policy = minimal_policy()
        policy["denylist"][0]["category"] = "spyware"
        with policy_file(policy) as path:
            with self.assertRaisesRegex(checker.PolicyError, "not declared"):
                checker.load_policy(path)

    def test_a_group_rule_outside_maven_is_rejected(self) -> None:
        policy = minimal_policy()
        policy["denylist"][1]["match"] = "group"
        with policy_file(policy) as path:
            with self.assertRaisesRegex(checker.PolicyError, "only defined for maven"):
                checker.load_policy(path)

    def test_an_exact_maven_rule_needs_a_full_coordinate(self) -> None:
        policy = minimal_policy()
        policy["denylist"][4]["match"] = "exact"
        with policy_file(policy) as path:
            with self.assertRaisesRegex(checker.PolicyError, "group:artifact"):
                checker.load_policy(path)

    def test_a_future_policy_version_is_refused_rather_than_guessed_at(self) -> None:
        with policy_file(minimal_policy(version=2)) as path:
            with self.assertRaisesRegex(checker.PolicyError, "unsupported policy"):
                checker.load_policy(path)

    def test_the_shipped_policy_has_no_unexplained_exceptions(self) -> None:
        # Not a rule the checker enforces — an exception is allowed to exist.
        # It is the state PRIVACY.md and docs/tracker-dependency-audit.md
        # describe, so a PR that adds one has to update them too, and this test
        # is where that gets noticed.
        policy = checker.load_policy(POLICY_PATH)
        self.assertEqual(
            policy.exceptions,
            (),
            "The shipped policy grants no exceptions. If that changes, update "
            "PRIVACY.md and docs/tracker-dependency-audit.md in the same PR.",
        )


# ---------------------------------------------------------------------------
# The real repository
# ---------------------------------------------------------------------------


class RealRepositoryTest(unittest.TestCase):
    def test_linthras_own_dependency_graph_passes(self) -> None:
        code, output = run(ROOT, POLICY_PATH)
        self.assertEqual(code, 0, output)
        self.assertIn("Advertising SDKs: none", output)
        self.assertIn("Analytics SDKs: none", output)
        self.assertIn("Automatic third-party crash reporting: none", output)

    def test_it_reads_every_source_it_claims_to(self) -> None:
        code, output = run(ROOT, POLICY_PATH)
        self.assertEqual(code, 0, output)
        for source in (
            "pubspec.lock",
            "flatpak/generated/sources/pubspec.json",
            "linux/flutter/generated_plugins.cmake",
            "android/app/build.gradle",
            "android/settings.gradle",
            "native/linthra_core/Cargo.lock",
        ):
            self.assertIn(source, output)

    def test_it_does_not_claim_to_prove_more_than_it_does(self) -> None:
        _, output = run(ROOT, POLICY_PATH)
        self.assertIn("does not prove", output)
        self.assertIn("docs/tracker-dependency-audit.md", output)

    def test_the_report_is_reproducible(self) -> None:
        first = run(ROOT, POLICY_PATH)
        second = run(ROOT, POLICY_PATH)
        self.assertEqual(first, second)

    def test_the_json_report_is_reproducible_and_says_it_passed(self) -> None:
        code, output = run(ROOT, POLICY_PATH, "--json")
        self.assertEqual(code, 0, output)
        report = json.loads(output)
        self.assertTrue(report["ok"])
        self.assertEqual(report["findings"], [])
        self.assertEqual(
            report["categories"], {key: 0 for key in report["categories"]}
        )
        self.assertEqual(output, run(ROOT, POLICY_PATH, "--json")[1])


# ---------------------------------------------------------------------------
# Catching a real one
# ---------------------------------------------------------------------------


class DisallowedDependencyTest(unittest.TestCase):
    def test_a_locked_analytics_package_fails(self) -> None:
        lock = CLEAN_LOCK.replace(
            "  audio_service:", "  firebase_analytics:\n    dependency: transitive\n"
            "    source: hosted\n    version: \"11.0.0\"\n  audio_service:"
        )
        with tree(lock=lock) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 1, output)
        self.assertIn("FAIL", output)

    def test_the_output_names_the_dependency_its_file_and_the_reason(self) -> None:
        sources = _clean_pub_sources("audio_service", "firebase_analytics")
        with tree(pub_sources=sources) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 1, output)
        self.assertIn("firebase_analytics", output)
        self.assertIn("flatpak/generated/sources/pubspec.json", output)
        self.assertIn("Reports app events to Google.", output)
        self.assertIn("Google (Firebase)", output)
        self.assertIn("Analytics SDKs", output)

    def test_a_finding_says_how_the_package_entered_the_graph(self) -> None:
        lock = CLEAN_LOCK.replace(
            "  audio_service:",
            '  amplitude_flutter:\n    dependency: "direct main"\n'
            '    source: hosted\n    version: "4.0.0"\n  audio_service:',
        )
        with tree(lock=lock) as root, policy_file(MINIMAL_POLICY) as policy:
            _, output = run(root, policy)
        self.assertIn("pubspec.lock (direct main)", output)

    def test_a_gradle_dependency_fails(self) -> None:
        gradle = CLEAN_GRADLE + """
dependencies {
    implementation "com.google.firebase:firebase-analytics:21.5.0"
}
"""
        with tree(gradle=gradle) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 1, output)
        self.assertIn("com.google.firebase:firebase-analytics", output)
        self.assertIn('maven group policy entry "com.google.firebase"', output)

    def test_a_gradle_plugin_fails(self) -> None:
        gradle = CLEAN_GRADLE.replace(
            '    id "kotlin-android"',
            '    id "kotlin-android"\n    id "com.google.gms.google-services"',
        )
        with tree(gradle=gradle) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 1, output)
        self.assertIn("com.google.gms.google-services", output)

    def test_the_kotlin_dsl_spelling_fails_too(self) -> None:
        with tree() as root, policy_file(MINIMAL_POLICY) as policy:
            (root / "android" / "app" / "build.gradle.kts").write_text(
                'dependencies {\n'
                '    implementation("com.google.firebase:firebase-crashlytics:19.0.0")\n'
                "}\n",
                encoding="utf-8",
            )
            code, output = run(root, policy)
        self.assertEqual(code, 1, output)
        self.assertIn("com.google.firebase:firebase-crashlytics", output)

    def test_a_crash_reporting_crate_fails(self) -> None:
        cargo = CLEAN_CARGO + '\n[[package]]\nname = "sentry"\nversion = "0.34.0"\n'
        with tree(cargo=cargo) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 1, output)
        self.assertIn("sentry", output)
        self.assertIn("Automatic third-party crash reporting", output)

    def test_a_plugin_linked_into_the_linux_binary_fails(self) -> None:
        cmake = CLEAN_CMAKE.replace(
            "  url_launcher_linux", "  url_launcher_linux\n  firebase_analytics"
        )
        with tree(cmake=cmake) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 1, output)
        self.assertIn("linux/flutter/generated_plugins.cmake", output)

    def test_one_dependency_in_two_files_is_reported_once_with_both(self) -> None:
        lock = CLEAN_LOCK.replace(
            "  audio_service:",
            '  firebase_analytics:\n    dependency: "direct main"\n'
            '    source: hosted\n    version: "11.0.0"\n  audio_service:',
        )
        sources = _clean_pub_sources("audio_service", "firebase_analytics")
        with tree(lock=lock, pub_sources=sources) as root:
            with policy_file(MINIMAL_POLICY) as policy:
                code, output = run(root, policy, "--json")
        self.assertEqual(code, 1, output)
        report = json.loads(output)
        self.assertEqual(len(report["findings"]), 1)
        self.assertEqual(
            [entry["source"] for entry in report["findings"][0]["found_in"]],
            ["flatpak/generated/sources/pubspec.json", "pubspec.lock"],
        )

    def test_a_group_rule_reports_each_coordinate_separately(self) -> None:
        # One policy line can match several artifacts. Collapsing them would
        # print one name and silently drop the rest, which is the one thing the
        # output must never do.
        gradle = CLEAN_GRADLE + """
dependencies {
    implementation "com.google.firebase:firebase-analytics:21.5.0"
    implementation "com.google.firebase:firebase-crashlytics:19.0.0"
}
"""
        with tree(gradle=gradle) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy, "--json")
        self.assertEqual(code, 1, output)
        report = json.loads(output)
        self.assertEqual(
            [finding["identifier"] for finding in report["findings"]],
            [
                "com.google.firebase:firebase-analytics",
                "com.google.firebase:firebase-crashlytics",
            ],
        )

    def test_the_failure_says_what_to_do_next(self) -> None:
        sources = _clean_pub_sources("firebase_analytics")
        with tree(pub_sources=sources) as root, policy_file(MINIMAL_POLICY) as policy:
            _, output = run(root, policy)
        self.assertIn("needs a human decision", output)
        self.assertIn("docs/tracker-dependency-audit.md", output)
        self.assertIn("exceptions", output)


# ---------------------------------------------------------------------------
# Not crying wolf
# ---------------------------------------------------------------------------


class NoFalsePositivesTest(unittest.TestCase):
    """A check that fires on innocent names gets switched off, and then it
    protects nothing. These are the names that a substring rule would flag."""

    def test_an_audio_package_that_reads_like_an_analytics_vendor_passes(self) -> None:
        # "amplitude" is an ordinary audio word. A music player will have
        # packages with it in the name; `amplitude_flutter` is the SDK.
        lock = CLEAN_LOCK.replace(
            "  audio_service:",
            "  amplitude_visualizer:\n    dependency: transitive\n"
            '    source: hosted\n    version: "1.2.0"\n  audio_service:',
        )
        with tree(lock=lock) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 0, output)

    def test_a_package_that_merely_starts_the_same_passes(self) -> None:
        lock = CLEAN_LOCK.replace(
            "  audio_service:",
            "  firebase_analytics_stub_for_tests:\n    dependency: transitive\n"
            '    source: hosted\n    version: "1.0.0"\n  audio_service:',
        )
        with tree(lock=lock) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 0, output)

    def test_a_maven_group_rule_does_not_swallow_a_longer_group(self) -> None:
        gradle = CLEAN_GRADLE + """
dependencies {
    implementation "com.google.firebaseui:firebase-ui-auth:8.0.2"
    implementation "com.google.android.material:material:1.11.0"
}
"""
        with tree(gradle=gradle) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 0, output)

    def test_a_vendor_named_in_a_comment_is_not_a_dependency(self) -> None:
        gradle = """\
// We deliberately do not use com.google.firebase:firebase-analytics here;
/* nor com.google.gms.google-services, see docs/fdroid-readiness.md */
plugins {
    id "com.android.application"
}
"""
        with tree(gradle=gradle) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 0, output)

    def test_a_url_in_a_gradle_file_is_not_a_maven_coordinate(self) -> None:
        gradle = CLEAN_GRADLE + """
repositories {
    maven { url "https://storage.googleapis.com/download.flutter.io" }
}
"""
        with tree(gradle=gradle) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 0, output)

    def test_applicationid_is_not_read_as_a_plugin_id(self) -> None:
        with tree() as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy, "--json")
        self.assertEqual(code, 0, output)
        report = json.loads(output)
        gradle = next(
            item
            for item in report["inspected"]
            if item["source"] == "android/app/build.gradle"
        )
        self.assertEqual(gradle["identifiers"], {"gradle plugin ids": 2})


# ---------------------------------------------------------------------------
# Reviewed exceptions
# ---------------------------------------------------------------------------


class ReviewedExceptionTest(unittest.TestCase):
    def test_a_reviewed_exception_lets_a_match_through_and_is_printed(self) -> None:
        policy = minimal_policy(
            exceptions=[
                {
                    "ecosystem": "dart",
                    "identifier": "firebase_analytics",
                    "sources": ["pubspec.lock"],
                    "reason": "Only here as a test fixture.",
                    "reviewed_in": "https://github.com/TheZupZup/Linthra/issues/504",
                }
            ]
        )
        lock = CLEAN_LOCK.replace(
            "  audio_service:",
            '  firebase_analytics:\n    dependency: "direct main"\n'
            '    source: hosted\n    version: "11.0.0"\n  audio_service:',
        )
        with tree(lock=lock) as root, policy_file(policy) as path:
            code, output = run(root, path)
        self.assertEqual(code, 0, output)
        self.assertIn("Reviewed exceptions in force:", output)
        self.assertIn("Only here as a test fixture.", output)

    def test_an_exception_is_scoped_to_the_files_it_names(self) -> None:
        policy = minimal_policy(
            exceptions=[
                {
                    "ecosystem": "dart",
                    "identifier": "firebase_analytics",
                    "sources": ["pubspec.lock"],
                    "reason": "Only excused in the lockfile.",
                    "reviewed_in": "https://github.com/TheZupZup/Linthra/issues/504",
                }
            ]
        )
        lock = CLEAN_LOCK.replace(
            "  audio_service:",
            '  firebase_analytics:\n    dependency: "direct main"\n'
            '    source: hosted\n    version: "11.0.0"\n  audio_service:',
        )
        sources = _clean_pub_sources("audio_service", "firebase_analytics")
        with tree(lock=lock, pub_sources=sources) as root, policy_file(policy) as path:
            code, output = run(root, path)
        self.assertEqual(code, 1, output)
        self.assertIn("flatpak/generated/sources/pubspec.json", output)

    def test_an_exception_that_matches_nothing_fails(self) -> None:
        # A reason may not outlive the dependency it explains, or the file
        # slowly becomes a list of things that used to be true.
        policy = minimal_policy(
            exceptions=[
                {
                    "ecosystem": "dart",
                    "identifier": "firebase_analytics",
                    "sources": ["pubspec.lock"],
                    "reason": "Removed three releases ago.",
                    "reviewed_in": "https://github.com/TheZupZup/Linthra/issues/504",
                }
            ]
        )
        with tree() as root, policy_file(policy) as path:
            code, output = run(root, path)
        self.assertEqual(code, 1, output)
        self.assertIn("matches nothing", output)

    def test_an_exception_without_a_reason_is_rejected(self) -> None:
        policy = minimal_policy(
            exceptions=[
                {
                    "ecosystem": "dart",
                    "identifier": "firebase_analytics",
                    "sources": ["pubspec.lock"],
                    "reviewed_in": "https://github.com/TheZupZup/Linthra/issues/504",
                }
            ]
        )
        with policy_file(policy) as path:
            with self.assertRaisesRegex(checker.PolicyError, "missing key"):
                checker.load_policy(path)


# ---------------------------------------------------------------------------
# Failing closed
# ---------------------------------------------------------------------------


class FailsClosedTest(unittest.TestCase):
    """A check that passes because its input vanished is worse than no check:
    it reports 'none' about a file nobody read."""

    def test_a_missing_source_file_is_an_error_not_a_pass(self) -> None:
        with tree() as root, policy_file(MINIMAL_POLICY) as policy:
            (root / "pubspec.lock").unlink()
            code, output = run(root, policy)
        self.assertEqual(code, 2, output)
        self.assertIn("pubspec.lock", output)

    def test_a_glob_that_matches_nothing_is_an_error(self) -> None:
        with tree() as root, policy_file(MINIMAL_POLICY) as policy:
            (root / "native" / "linthra_core" / "Cargo.lock").unlink()
            code, output = run(root, policy)
        self.assertEqual(code, 2, output)
        self.assertIn("Cargo.lock", output)

    def test_a_lockfile_entry_without_a_kind_is_an_error(self) -> None:
        lock = "packages:\n  audio_service:\n    source: hosted\n    version: \"1\"\n"
        with tree(lock=lock) as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 2, output)
        self.assertIn("dependency", output)

    def test_an_empty_lockfile_is_an_error(self) -> None:
        with tree(lock="packages:\n") as root, policy_file(MINIMAL_POLICY) as policy:
            code, output = run(root, policy)
        self.assertEqual(code, 2, output)

    def test_a_cmake_file_with_no_plugin_list_is_an_error(self) -> None:
        with tree(cmake="# nothing here\n") as root:
            with policy_file(MINIMAL_POLICY) as policy:
                code, output = run(root, policy)
        self.assertEqual(code, 2, output)

    def test_an_unreadable_policy_is_an_error_not_a_pass(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "tracker_policy.json"
            path.write_text("{ not json", encoding="utf-8")
            with tree() as root:
                code, output = run(root, path)
        self.assertEqual(code, 2, output)
        self.assertIn("not valid JSON", output)


# ---------------------------------------------------------------------------
# Parsers, on their own
# ---------------------------------------------------------------------------


class ParserTest(unittest.TestCase):
    def test_the_lockfile_sdk_block_is_not_read_as_a_package(self) -> None:
        names = {o.identifier for o in checker.parse_pubspec_lock(CLEAN_LOCK)}
        self.assertEqual(names, {"audio_service", "flutter"})

    def test_the_lockfile_kind_is_kept(self) -> None:
        kinds = {o.identifier: o.detail for o in checker.parse_pubspec_lock(CLEAN_LOCK)}
        self.assertEqual(kinds["audio_service"], "direct main")

    def test_a_pub_version_with_a_dash_still_yields_the_package_name(self) -> None:
        sources = json.dumps(
            [
                {
                    "type": "archive",
                    "dest": ".pub-cache/hosted/pub.dev/just_audio-0.9.42-beta.1",
                },
                {
                    "type": "inline",
                    "dest": ".pub-cache/hosted-hashes/pub.dev",
                },
            ]
        )
        found = checker.parse_flatpak_pub_sources(sources, "pubspec.json")
        self.assertEqual([o.identifier for o in found], ["just_audio"])

    def test_gradle_comments_are_stripped_without_eating_urls(self) -> None:
        stripped, literals = checker.strip_gradle_comments(
            'maven { url "https://pub.dev" } // a comment\n'
        )
        self.assertIn("https://pub.dev", stripped)
        self.assertNotIn("a comment", stripped)
        self.assertEqual(literals, ["https://pub.dev"])

    def test_a_triple_quoted_string_does_not_swallow_the_rest_of_the_file(self) -> None:
        gradle = "def notes = '''nothing to see'''\nplugins { id \"kotlin-android\" }\n"
        found = checker.parse_gradle(gradle, "build.gradle")
        self.assertEqual(
            [o.identifier for o in found if o.ecosystem == "gradle-plugin"],
            ["kotlin-android"],
        )

    def test_apply_plugin_is_read_as_a_plugin_id(self) -> None:
        found = checker.parse_gradle(
            "apply plugin: 'com.google.gms.google-services'\n", "build.gradle"
        )
        self.assertIn("com.google.gms.google-services", [o.identifier for o in found])

    def test_a_coordinate_without_a_version_is_still_a_coordinate(self) -> None:
        found = checker.parse_gradle(
            'implementation "io.sentry:sentry-android"\n', "build.gradle"
        )
        self.assertEqual(
            [o.identifier for o in found if o.ecosystem == "maven"],
            ["io.sentry:sentry-android"],
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
