#!/usr/bin/env python3
"""Derive the audio-smoke Flatpak manifest from the submission manifest (#446).

The Flatpak audio smoke has to run against the packaged libmpv, which means it
has to run from inside an installed Flatpak. That needs a second Flutter binary
in the package, and the submission manifest must not carry one: a test harness
in a published app is dead weight a Flathub reviewer would rightly ask about.

So CI builds a manifest derived from the submission manifest here, and this
script is what makes "derived" a checkable claim rather than a promise. It
appends the smoke build/install commands to the `linthra` module and then
proves that nothing else moved: the generated manifest is re-parsed, the
appended commands are removed again, and the result must equal the submission
manifest exactly. Runtime, SDK, every library module, every source and every
finish-arg are therefore identical by construction, and a manifest regenerated
by flatpak-flutter into a different shape fails here instead of quietly
producing a package the smoke no longer describes.

The output is a build artifact. It is written next to the submission manifest
so the relative source paths inside it still resolve, and it is git-ignored.

Usage:
    python3 scripts/make_flatpak_smoke_manifest.py [--manifest P] [--output P]
"""

from __future__ import annotations

import argparse
import copy
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = REPO_ROOT / "flatpak" / "io.github.thezupzup.linthra.yml"
DEFAULT_OUTPUT = REPO_ROOT / "flatpak" / "io.github.thezupzup.linthra.sandbox-smoke.yml"

APP_MODULE = "linthra"

#: Every smoke binary the derived manifest installs, by the name a harness asks
#: for it under. Each lands in its own directory under /app/libexec rather than
#: /app/bin, so none can be mistaken for something a user runs or shadow the
#: real `linthra` command on PATH.
#:
#: They share one manifest, and therefore one build, deliberately: a second
#: derived manifest would mean a second 90-minute flatpak-builder run to test a
#: package that differs from this one by a directory.
SMOKE_TARGETS = {
    "audio": "tool/linux_audio_backend_smoke.dart",
    "local-library": "tool/linux_local_library_smoke.dart",
}


def install_dir(name: str) -> str:
    return f"/app/libexec/linthra-{name}-smoke"


def smoke_command(name: str) -> str:
    """The in-sandbox path of one smoke binary.

    `linthra` is the binary name the Flutter Linux runner produces for every
    target, so the directory is what tells the bundles apart.
    """
    if name not in SMOKE_TARGETS:
        raise KeyError(name)
    return f"{install_dir(name)}/linthra"


def build_commands_for(name: str) -> list[str]:
    """The commands that build and install one smoke binary.

    `flutter build linux` always writes to the same bundle directory, so each
    build overwrites the last one's output, which is why every target copies
    its bundle out before the next build runs, and why all of this has to come
    after the app has been copied into /app.
    """
    target = SMOKE_TARGETS[name]
    destination = install_dir(name)
    return [
        f"flutter build linux --release --no-pub --target={target}",
        f"install -d {destination}",
        f"cp -r build/linux/x64/release/bundle/. {destination}/",
    ]


#: Commands appended to the app module, after it has installed the real app.
SMOKE_BUILD_COMMANDS = [
    command for name in SMOKE_TARGETS for command in build_commands_for(name)
]

#: Commands the app module must already contain, in this order, for the
#: appended ones above to mean what they say: the app is built, then copied out
#: of the bundle directory the smoke build is about to overwrite.
REQUIRED_APP_COMMANDS = [
    "flutter build linux --release --no-pub",
    "cp -r build/linux/x64/release/bundle/. /app/lib/linthra/",
]

HEADER = """\
# DO NOT EDIT, DO NOT COMMIT, DO NOT SUBMIT.
#
# Generated by scripts/make_flatpak_smoke_manifest.py from
# {manifest}
#
# This is the submission manifest plus the extra installed directories below,
# each holding one Flutter smoke binary:
#
{targets}
#
# Nothing else differs, and the generator fails if it does. They exist so the
# sandbox smokes run against the package this manifest builds rather than
# whatever the host happens to have (#446, #447).
"""


class ManifestShapeError(RuntimeError):
    """The submission manifest is not the shape this generator understands."""


def find_app_module(manifest: dict) -> dict:
    """Return the `linthra` module, or explain why it could not be found."""
    modules = manifest.get("modules")
    if not isinstance(modules, list):
        raise ManifestShapeError("the manifest has no `modules` list.")
    for module in modules:
        if isinstance(module, dict) and module.get("name") == APP_MODULE:
            return module
    raise ManifestShapeError(
        "the manifest has no module named {!r}.".format(APP_MODULE)
    )


def check_app_commands(commands: object) -> list:
    """Hold the app module to the build steps the appended ones depend on."""
    if not isinstance(commands, list):
        raise ManifestShapeError(
            "module {!r} has no `build-commands` list.".format(APP_MODULE)
        )
    missing = [c for c in REQUIRED_APP_COMMANDS if c not in commands]
    if missing:
        raise ManifestShapeError(
            "module {!r} no longer runs: {}. The smoke manifest builds on "
            "those exact steps; re-check the generated manifest before "
            "updating this script.".format(APP_MODULE, ", ".join(missing))
        )
    order = [commands.index(c) for c in REQUIRED_APP_COMMANDS]
    if order != sorted(order):
        raise ManifestShapeError(
            "module {!r} builds the app after copying the bundle out of it, "
            "so appending the smoke build would ship the wrong binary.".format(
                APP_MODULE
            )
        )
    for command in SMOKE_BUILD_COMMANDS:
        if command in commands:
            raise ManifestShapeError(
                "module {!r} already runs {!r}: the submission manifest must "
                "not carry the smoke harness.".format(APP_MODULE, command)
            )
    return commands


def build_smoke_manifest(manifest: dict) -> dict:
    """Return a copy of [manifest] with the smoke build appended."""
    smoke = copy.deepcopy(manifest)
    module = find_app_module(smoke)
    commands = check_app_commands(module.get("build-commands"))
    module["build-commands"] = commands + list(SMOKE_BUILD_COMMANDS)
    return smoke


def assert_only_smoke_commands_added(original: dict, smoke: dict) -> None:
    """Fail unless [smoke] is [original] plus exactly the smoke commands.

    This is the check that lets the workflow, the docs and a reviewer treat the
    built package as the submission package: undo the one documented edit, and
    what is left has to be byte-for-byte the same manifest.
    """
    rebuilt = copy.deepcopy(smoke)
    module = find_app_module(rebuilt)
    commands = module.get("build-commands")
    tail = commands[-len(SMOKE_BUILD_COMMANDS) :]
    if tail != list(SMOKE_BUILD_COMMANDS):
        raise ManifestShapeError(
            "the generated manifest does not end with the smoke commands."
        )
    module["build-commands"] = commands[: -len(SMOKE_BUILD_COMMANDS)]
    if rebuilt != original:
        raise ManifestShapeError(
            "the generated manifest differs from the submission manifest by "
            "more than the smoke build commands."
        )


def render(manifest: dict, source: Path) -> str:
    try:
        shown = source.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        shown = source.as_posix()
    targets = "\n".join(
        "#   {} <- {}".format(install_dir(name), SMOKE_TARGETS[name])
        for name in sorted(SMOKE_TARGETS)
    )
    header = HEADER.format(manifest=shown, targets=targets)
    # `width` is deliberately enormous. PyYAML folds long plain scalars onto a
    # continuation line by default, which is valid YAML but turns every install
    # command into two lines a reader has to rejoin mentally before they can
    # compare this file against the manifest it came from.
    body = yaml.safe_dump(
        manifest,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=10**6,
    )
    return header + "\n" + body


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="submission manifest to derive from",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="where to write the generated smoke manifest",
    )
    parser.add_argument(
        "--print-command",
        metavar="NAME",
        choices=sorted(SMOKE_TARGETS),
        help="print the in-sandbox path of one smoke binary and exit "
        "(one of: {})".format(", ".join(sorted(SMOKE_TARGETS))),
    )
    args = parser.parse_args(argv)

    if args.print_command:
        print(smoke_command(args.print_command))
        return 0

    try:
        original = yaml.safe_load(args.manifest.read_text(encoding="utf-8"))
    except OSError as error:
        print("ERROR: cannot read {}: {}".format(args.manifest, error), file=sys.stderr)
        return 1

    try:
        smoke = build_smoke_manifest(original)
        assert_only_smoke_commands_added(original, smoke)
    except ManifestShapeError as error:
        print("ERROR: {}".format(error), file=sys.stderr)
        return 1

    args.output.write_text(render(smoke, args.manifest), encoding="utf-8")
    print("Wrote {} from {}.".format(args.output, args.manifest))
    print("Added to module {!r}:".format(APP_MODULE))
    for command in SMOKE_BUILD_COMMANDS:
        print("  {}".format(command))
    print("Smoke commands inside the sandbox:")
    for name in sorted(SMOKE_TARGETS):
        print("  {:<14} {}".format(name, smoke_command(name)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
